name: flutter_application_1
description: "Explore Oman Flutter app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.8.0
  firebase_auth: ^6.5.0
  cupertino_icons: ^1.0.8
  firebase_database: ^12.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg.jpg
